import { Router } from 'express';
import { authRouter } from '../features/auth/auth.routes.js';
import { pantryRouter } from '../features/pantry/pantry.routes.js';
import { paymentRouter } from '../features/payments/routes.js';
import { receiptRouter } from '../features/receipts/receipt.routes.js';
import { recipesRouter } from '../features/recipes/recipe.routes.js';
import { vendorRouter } from '../features/vendors/routes.js';
import { createFeatureRouter } from '../shared/http/create-feature-router.js';

export const apiRouter = Router();
apiRouter.use('/auth', authRouter);
apiRouter.use('/receipts', receiptRouter);
apiRouter.use('/pantry', pantryRouter);
apiRouter.use('/recipes', recipesRouter);
apiRouter.use('/grocery-lists', createFeatureRouter('smart grocery lists'));
apiRouter.use('/prices', createFeatureRouter('neighbourhood prices'));
apiRouter.use('/impact', createFeatureRouter('nutrition and environmental impact'));
apiRouter.use('/community', createFeatureRouter('community baskets and group orders'));
apiRouter.use('/vendors', vendorRouter);
apiRouter.use('/payments', paymentRouter);
