import { Router } from 'express';
import { authRouter } from '../features/auth/auth.routes.js';
import { pantryRouter } from '../features/pantry/pantry.routes.js';
import { receiptRouter } from '../features/receipts/receipt.routes.js';
import { cookingSessionsRouter, groceryListItemsRouter, pantryConsumptionRouter, recipesRouter } from '../features/recipes/routes.js';
import { createFeatureRouter } from '../shared/http/create-feature-router.js';

export const apiRouter = Router();
apiRouter.use('/auth', authRouter);
apiRouter.use('/receipts', receiptRouter);
apiRouter.use('/pantry', pantryConsumptionRouter);
apiRouter.use('/pantry', pantryRouter);
apiRouter.use('/recipes', recipesRouter);
apiRouter.use('/grocery-lists', groceryListItemsRouter);
apiRouter.use('/grocery-lists', createFeatureRouter('smart grocery lists'));
apiRouter.use('/cooking-sessions', cookingSessionsRouter);
apiRouter.use('/prices', createFeatureRouter('neighbourhood prices'));
apiRouter.use('/impact', createFeatureRouter('nutrition and environmental impact'));
apiRouter.use('/community', createFeatureRouter('community baskets and group orders'));
apiRouter.use('/vendors', createFeatureRouter('local farmers and vendors'));
apiRouter.use('/payments', createFeatureRouter('Stripe payments'));
